# Generated by Django 3.1.5 on 2021-01-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_preferences', '0006_auto_20191001_2236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='globalpreferencemodel',
            table='configurations',
        ),
    ]
